name: build
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: killvxk/llvm-msvc-ex

      - name: MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        shell: pwsh
        run: |
          New-Item -Force -ItemType Container -Path build
          Set-Location -Path build
          cmake `
            .. `
            -G 'Visual Studio 17 2022' `
            -A X64 `
            -DCMAKE_C_FLAGS='/utf-8' `
            -DCMAKE_CXX_FLAGS='/utf-8' `
            -DHAVE_STD_IS_TRIVIALLY_COPYABLE=0 `
            -DLLVM_TOOL_LLVM_SHLIB_BUILD=off `
            -DLLDB_ENABLE_PYTHON=OFF `
            -DLLVM_INCLUDE_TESTS=OFF `
            -DLLVM_INCLUDE_EXAMPLES=OFF `
            -DLLVM_ENABLE_PROJECTS="clang;lld;lldb" `
            -DCMAKE_INSTALL_PREFIX="$(-Join((Get-Location).Path, '\..\release'))" `
            -DLLVM_ENABLE_LIBXML2=OFF `
            -DLLVM_ENABLE_ZLIB=OFF `
            -DLLVM_TARGETS_TO_BUILD=X86 `
            -DLLVM_OBFUSCATION_LINK_INTO_TOOLS=ON `
            -DCMAKE_BUILD_TYPE=release `
            -DLLVM_USE_CRT_RELEASE=MT `
            ..\llvm
          msbuild `
            /m `
            /p:Configuration=Release `
            INSTALL.vcxproj
          Set-Location -Path ..

      - name: Final
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release
          if-no-files-found: error

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
