on:
  workflow_dispatch:

name: 'Aarch64 None ELF'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: killvxk/llvm-msvc-ex
          submodules: recursive

      - name: Setup
        run: |
          sudo apt update
          sudo apt install build-essential ninja-build p7zip-full cmake make -y
          sudo apt install libstdc++-10-dev-arm64-cross g++-10-aarch64-linux-gnu g++-10 gcc-10 -y

      - name: Build
        run: |
          cmake -GNinja -Bbuild \
            -DCMAKE_INSTALL_PREFIX=install \
            -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_INCLUDE_TOOLS=ON \
            -DLLVM_INCLUDE_EXAMPLES=OFF \
            -DLLVM_ENABLE_ASSERTIONS=OFF \
            -DLLDB_ENABLE_PYTHON=OFF \
            -DLLVM_ENABLE_LIBXML2=OFF \
            -DLLVM_ENABLE_ZLIB=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_TARGET_ARCH=AArch64 \
            -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64;Mips;RISCV" \
            -DLLVM_ENABLE_PROJECTS="clang;lld;lldb;clang-tools-extra" \
            -DLLVM_HOST_TRIPLE="x86_64-pc-linux-gnu" \
            -DLLVM_TARGET_TRIPLE="aarch64-none-elf" \
            -DLLVM_DEFAULT_TARGET_TRIPLE="aarch64-none-elf" \
            llvm
            cmake --build build --config Release
            cmake --build build --config Release --target install

      - name: Final
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-non-elf
          path: install
          if-no-files-found: error

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
