on:
  workflow_dispatch:

name: build

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: killvxk/llvm-msvc-ex
          submodules: recursive

      - name: MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup
        shell: pwsh
        run: |
          $date = Get-Date -Format 'yyyyMMdd'
          $time = Get-Date -Format 'HHmmss'

          "DATE=$date" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          "TIME=$time" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          "DATETIME=$date-$time" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build
        shell: pwsh
        run: |
          cmake `
            -G 'Visual Studio 18 2026' `
            -A x64 `
            -B build `
            -DCMAKE_C_FLAGS='/utf-8' `
            -DCMAKE_CXX_FLAGS='/utf-8' `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_INSTALL_PREFIX='release' `
            -DHAVE_STD_IS_TRIVIALLY_COPYABLE=0 `
            -DLLDB_ENABLE_PYTHON=OFF `
            -DLLVM_ENABLE_LIBXML2=OFF `
            -DLLVM_ENABLE_PROJECTS='lld;lldb;clang;clang-tools-extra' `
            -DLLVM_ENABLE_RPMALLOC=ON `
            -DLLVM_ENABLE_ZLIB=OFF `
            -DLLVM_INCLUDE_BENCHMARKS=OFF `
            -DLLVM_INCLUDE_EXAMPLES=OFF `
            -DLLVM_INCLUDE_TESTS=OFF `
            -DLLVM_INCLUDE_TOOLS=ON `
            -DLLVM_OBFUSCATION_LINK_INTO_TOOLS=ON `
            -DLLVM_TARGETS_TO_BUILD='X86' `
            -DLLVM_TOOL_LLVM_SHLIB_BUILD=OFF `
            -DLLVM_USE_CRT_RELEASE=MT `
            llvm
          cmake --build build --config Release --verbose
          cmake --build build --config Release --target install --verbose
          7z a LLVM-MSVC-${{ env.DATETIME }}.7z release

      - name: Push
        uses: softprops/action-gh-release@v2
        with:
          files: |
            LLVM-MSVC-${{ env.DATETIME }}.7z
          tag_name: v${{ env.DATETIME }}
          make_latest: true
          generate_release_notes: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
