on:
  workflow_dispatch:

name: aarch64-none-elf

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: killvxk/llvm-msvc-ex
          submodules: recursive

      - name: Setup
        run: |
          sudo apt update
          sudo apt install build-essential ninja-build p7zip-full cmake make -y
          sudo apt install libstdc++-10-dev-arm64-cross g++-10-aarch64-linux-gnu g++-10 gcc-10 -y

      - name: Build
        run: |
          cmake \
            -G Ninja \
            -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX='release' \
            -DLLDB_ENABLE_PYTHON=OFF \
            -DLLVM_ENABLE_LIBXML2=OFF \
            -DLLVM_ENABLE_PROJECTS='lld;lldb;clang;clang-tools-extra' \
            -DLLVM_ENABLE_RPMALLOC=ON \
            -DLLVM_ENABLE_ZLIB=OFF \
            -DLLVM_INCLUDE_BENCHMARKS=OFF \
            -DLLVM_INCLUDE_EXAMPLES=OFF \
            -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_INCLUDE_TOOLS=ON \
            -DLLVM_OBFUSCATION_LINK_INTO_TOOLS=ON \
            -DLLVM_HOST_TRIPLE='x86_64-pc-linux-gnu' \
            -DLLVM_TARGET_ARCH='AArch64' \
            -DLLVM_TARGET_TRIPLE='aarch64-none-elf' \
            -DLLVM_DEFAULT_TARGET_TRIPLE='aarch64-none-elf' \
            -DLLVM_TARGETS_TO_BUILD='AArch64' \
            llvm
          cmake --build build --config Release --verbose
          cmake --build build --config Release --target install --verbose

      - name: Final
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
