on:
  push:
  workflow_dispatch:

name: windows-x64

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: killvxk/llvm-msvc-ex
          submodules: recursive

      - name: MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        shell: pwsh
        run: |
          cmake `
            -G 'Visual Studio 17 2022' `
            -A x64 `
            -B build `
            -DCMAKE_C_FLAGS='/utf-8' `
            -DCMAKE_CXX_FLAGS='/utf-8' `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_INSTALL_PREFIX='release' `
            -DHAVE_STD_IS_TRIVIALLY_COPYABLE=0 `
            -DLLDB_ENABLE_PYTHON=OFF `
            -DLLVM_ENABLE_LIBXML2=OFF `
            -DLLVM_ENABLE_PROJECTS='lld;lldb;clang;clang-tools-extra' `
            -DLLVM_ENABLE_RPMALLOC=ON `
            -DLLVM_ENABLE_ZLIB=OFF `
            -DLLVM_INCLUDE_BENCHMARKS=OFF `
            -DLLVM_INCLUDE_EXAMPLES=OFF `
            -DLLVM_INCLUDE_TESTS=OFF `
            -DLLVM_INCLUDE_TOOLS=ON `
            -DLLVM_OBFUSCATION_LINK_INTO_TOOLS=ON `
            -DLLVM_TARGETS_TO_BUILD='X86' `
            -DLLVM_TOOL_LLVM_SHLIB_BUILD=OFF `
            -DLLVM_USE_CRT_RELEASE=MT `
            llvm
          cmake --build build --config Release --verbose
          cmake --build build --config Release --target install --verbose

      - name: Final
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
